# coding=utf-8

from unittest.case import TestCase
from ellipticcurve.ecdsa import Ecdsa
from ellipticcurve.privateKey import PrivateKey
from ellipticcurve.publicKey import PublicKey
from ellipticcurve.signature import Signature


class OpensslTest(TestCase):

    def testAssign(self):
        # Generated by: openssl ecparam -name secp256k1 -genkey -out privateKey.pem
        with open("test/privateKey.pem") as fh:
            privateKeyPem = fh.read()

        privateKey = PrivateKey.fromPem(privateKeyPem)

        with open("test/message.txt") as fh:
            message = fh.read()

        signature = Ecdsa.sign(message=message, privateKey=privateKey)

        publicKey = privateKey.publicKey()

        self.assertTrue(Ecdsa.verify(message=message, signature=signature, publicKey=publicKey))

    def testVerifySignature(self):
        # openssl ec -in privateKey.pem -pubout -out publicKey.pem
        with open("test/publicKey.pem") as fh:
            publicKeyPem = fh.read()

        # openssl dgst -sha256 -sign privateKey.pem -out signature.binary message.txt
        with open("test/signatureDer.txt", 'rb') as fh:
            signatureDer = fh.read()

        with open("test/message.txt") as fh:
            message = fh.read()

        publicKey = PublicKey.fromPem(publicKeyPem)

        signature = Signature.fromDer(string=signatureDer)

        self.assertTrue(Ecdsa.verify(message=message, signature=signature, publicKey=publicKey))
