language: python

matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "3.10"
    - python: "3.11"
    - python: "3.12"
    - python: "3.13"
    - python: "pypy2.7-7.3.9"
    - python: "pypy3.10"

script:
  - python -m unittest discover
