from os.path import dirname, join
from unittest.case import TestCase
from ellipticcurve import Ecdsa, PrivateKey, PublicKey, Signature, File


FIXTURES = dirname(__file__)


class OpensslTest(TestCase):

    def testAssign(self):
        # Generated by: openssl ecparam -name secp256k1 -genkey -out privateKey.pem
        privateKeyPem = File.read(join(FIXTURES, "privateKey.pem"))

        privateKey = PrivateKey.fromPem(privateKeyPem)

        message = File.read(join(FIXTURES, "message.txt"))

        signature = Ecdsa.sign(message=message, privateKey=privateKey)

        publicKey = privateKey.publicKey()

        self.assertTrue(Ecdsa.verify(message=message, signature=signature, publicKey=publicKey))

    def testVerifySignature(self):
        # openssl ec -in privateKey.pem -pubout -out publicKey.pem

        publicKeyPem = File.read(join(FIXTURES, "publicKey.pem"))

        # openssl dgst -sha256 -sign privateKey.pem -out signature.binary message.txt
        signatureDer = File.read(join(FIXTURES, "signatureDer.txt"), "rb")

        message = File.read(join(FIXTURES, "message.txt"))

        publicKey = PublicKey.fromPem(publicKeyPem)

        signature = Signature.fromDer(string=signatureDer)

        self.assertTrue(Ecdsa.verify(message=message, signature=signature, publicKey=publicKey))
